# Generated by Django 4.2.21 on 2025-05-26 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
        ('movies', '0004_movie_cast_movie_director_movie_genres_and_more'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='emotions.emotion'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='movies.movie'),
        ),
    ]
