# Generated by Django 4.2.21 on 2025-05-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_runtime'),
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_connections', to='emotions.emotion')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_connections', to='movies.movie')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('movie', 'emotion')},
            },
        ),
    ]
