# Generated by Django 4.2.21 on 2025-05-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='color_palette',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dominant_color',
        ),
    ]
