# Generated by Django 4.2.21 on 2025-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_color_palette_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='external_rating',
            new_name='vote_average',
        ),
    ]
