# Generated by Django 4.2.21 on 2025-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_cast_movie_director_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
